query($section:[String], $orderBy:String) {
    entries(section: $section, orderBy: $orderBy) {
        title,
        uri,
        postDate @formatDateTime (format: "F jS Y"),
        ... on activity_Activity_Entry{
            fontColor,
            backgroundColor,
            richText
        }
    }
}