query($section:[String], $orderBy:String, $relatedTo:[Int]) {
    entries(section: $section, orderBy: $orderBy, relatedTo: $relatedTo) {
        title,
        uri,
        slug,
        postDate @formatDateTime (format: "F jS Y"),
        ... on work_work_Entry{
            fontColor,
            backgroundColor,
            contentEngine{
                __typename,
            },
            logo {
                url
            },
            thumbnail{
                url
            }
        }
    }
}