query($section:[String], $orderBy:String) {
  entries(section: $section, orderBy: $orderBy) {
    title,
    uri,
    postDate @formatDateTime (format: "F jS Y"),
    ... on blog_blog_Entry{
      fontColor,
      backgroundColor 
    }
  }
}